### ISSUE TITLE
你好，特征都已经提取到CSV文件里了，能不能通过CSV文件直接进行模型训练

### ISSUE THREAD

**Issue by ZevaXu** [easylearn-fmri/easylearn_dev#53]
你好，特征都已经提取到CSV文件里了，能不能通过CSV文件直接进行模型训练

**Comment by lichao312214129** [comment]
您好，只要特征和标签已经准备好了，而且按照我视频和Word教程中的格式准备好了，就可以顺利运行。

**Comment by ZevaXu** [comment]
谢谢回复，但是我没有找到相关教程和视频，请问在哪里能够获取呢？感谢！

**Comment by ZevaXu** [comment]
> 您好，只要特征和标签已经准备好了，而且按照我视频和Word教程中的格式准备好了，就可以顺利运行。

python运行的GUI界面中，上方有Help 按钮，但是点击后没有反映

**Comment by lichao312214129** [comment]
大家好，easylearn操作视频已上传b站：https://m.bilibili.com/video/BV1Vr4y1T7qJ

*********************************************
欢迎使用和引用easylearn
本群可以讨论任何关于机器学习的问题

以下是安装和使用easylearn的教程
百度网盘链接：https://pan.baidu.com/s/1Pb6E-6R6zJ_VCytyqWYQ4w 
提取码：qie2 
************************************************

*easylearn使命：让机器学习简单且严谨！
*easylearn愿景：让每一位想做机器学习的医生和研究者都能轻松且正确的完成机器学习！
*easylearn的价值观：恪守科研伦理，崇尚科学真理，助力科研和临床的发展！

软件链接之最新版本：https://github.com/easylearn-fmri/easylearn_dev

软件链接之稳定版本：
https://github.com/lichao312214129/easylearn

**Comment by lichao312214129** [comment]
您好，百度网盘链接中的eslearn教程word最后有入微信交流群的方式

**Comment by ZevaXu** [comment]
> 您好，百度网盘链接中的eslearn教程word最后有入微信交流群的方式

非常感谢您的回复！
